services:
  localstack:
    image: localstack/localstack
    container_name: dynamo-db-localstack
    ports:
      - "4566:4566"
    env_file:     
      - .env
    environment:
      - SERVICES=dynamodb,s3,lambda
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=${REGION_NAME}
    networks:
      - recipe-app-network

  db-service:
    image: db-microservice
    build: ./db-microservice
    ports:
      - "8004"
    env_file:
      - .env
    depends_on:
      - localstack
    environment:
      - DYNAMO_ENDPOINT=${DYNAMODB_ENDPOINT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=${REGION_NAME}
    networks:
      - recipe-app-network
    deploy:
      replicas: 1


  auth:
    image: auth-microservice
    build: ./auth-microservice
    ports:
      - "8001"
    env_file:     
      - .env
    environment:
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db-service
    networks:
      - recipe-app-network
    deploy:
      replicas: 2

  recommendation:
    image: recommendation-microservice
    build: ./recommendation-microservice
    ports:
      - "8003"
    env_file:     
      - .env
    depends_on:
      - db-service
    networks:
      - recipe-app-network
    deploy:
      replicas: 2

  classic:
    image: classic-microservice
    build: ./classic-microservice
    ports:
      - "8002"
    env_file:     
      - .env
    depends_on:
      - auth
      - recommendation
      - db-service
    environment:
      - DATABASE_SERVICE_ENDPOINT=http://nginx/db
    networks:
      - recipe-app-network
    deploy:
      replicas: 2

  nginx: 
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - classic
      - auth
      - recommendation
      - db-service
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - recipe-app-network

networks:
  recipe-app-network:
    driver: bridge
